### PR TITLE
Working project

### PR DESCRIPTION
**Pull request by bellaj**
the returned SetupReturn object should have the computed pub and msk key

### CODE REVIEW

**Comment by bellaj** [comment]
alt text

**Comment by bellaj** [comment]
@ImaneNouhi 
I have forgotten to add       
          setR.pub.g_hat_alpha=pub.g_hat_alpha;
before returning the object (see below selected part in the picture)

**Comment by ImaneNouhi** [comment]
I am really greatful for your intervention, when I ve added this line he
turns to null pointer again error in that line. actually g-hat-alpha has
been calculated and showed before, why should we add that line ?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
23/06/18
à 22:45:32

**Comment by bellaj** [comment]
remove it 
but it should not give you a null error !!!

**Comment by ImaneNouhi** [comment]
actually it should, becuse the setR.pub objet has not built or initialized
yet at that line. but anyway I can't thank you enough for you help. :D

**Comment by bellaj** [comment]
this is my working version
https://github.com/bellaj/Pcabe

**Comment by bellaj** [comment]
it shouldn't rise a null pointer as 
setR.pub=pub !!! so it's initialized
there is no need to set setR.pub.g_hat_alpha 
as it's already set in pub

**Comment by ImaneNouhi** [comment]
it is working thanks a lot :D

**Pull request merged**
